export const OPEN_LEFT_DRAWER = "OPEN_LEFT_DRAWER";
export const CLOSE_LEFT_DRAWER = "CLOSE_LEFT_DRAWER";

export const OPEN_BOTTOM_DRAWER = "OPEN_BOTTOM_DRAWER";
export const CLOSE_BOTTOM_DRAWER = "CLOSE_BOTTOM_DRAWER";

export const CHANGE_GROUP = "CHANGE_GROUP";

export const LOAD_TIMETABLE_REQUEST = "LOAD_TIMETABLE_REQUEST";
export const LOAD_TIMETABLE_FAILURE = "LOAD_TIMETABLE_FAILURE";
export const LOAD_TIMETABLE_SUCCESS = "LOAD_TIMETABLE_SUCCESS";

export const LOAD_CONFIGURATION_REQUEST = "LOAD_CONFIGURATION_REQUEST";
export const LOAD_CONFIGURATION_SUCCESS = "LOAD_CONFIGURATION_SUCCESS";
