export const OPEN_LEFT_DRAWER = "OPEN_LEFT_DRAWER";
export const CLOSE_LEFT_DRAWER = "CLOSE_LEFT_DRAWER";

export const OPEN_BOTTOM_DRAWER = "OPEN_BOTTOM_DRAWER";
export const CLOSE_BOTTOM_DRAWER = "CLOSE_BOTTOM_DRAWER";
